// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { GameState as __GameState } from "./game_state_type";

export type Game = {
  id: number,
  name: string,
  spaceScore: number,
  timeScore: number,
  remaining: number,
  state: __GameState,
  mvp: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Game {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU8Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("spaceScore", AlgebraicType.createI32Type()),
      new ProductTypeElement("timeScore", AlgebraicType.createI32Type()),
      new ProductTypeElement("remaining", AlgebraicType.createI8Type()),
      new ProductTypeElement("state", __GameState.getTypeScriptAlgebraicType()),
      new ProductTypeElement("mvp", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Game): void {
    Game.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Game {
    return Game.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


