// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// A namespace for generated variants and helper functions.
export namespace GameState {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type Waiting = { tag: "Waiting" };
  export type Reset = { tag: "Reset" };
  export type GameStarted = { tag: "GameStarted" };
  export type SpaceScored = { tag: "SpaceScored" };
  export type TimeScored = { tag: "TimeScored" };
  export type GameEndedInSpaceWin = { tag: "GameEndedInSpaceWin" };
  export type GameEndedInTimeWin = { tag: "GameEndedInTimeWin" };
  export type GameEndedInTie = { tag: "GameEndedInTie" };

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const Waiting = { tag: "Waiting" };
  export const Reset = { tag: "Reset" };
  export const GameStarted = { tag: "GameStarted" };
  export const SpaceScored = { tag: "SpaceScored" };
  export const TimeScored = { tag: "TimeScored" };
  export const GameEndedInSpaceWin = { tag: "GameEndedInSpaceWin" };
  export const GameEndedInTimeWin = { tag: "GameEndedInTimeWin" };
  export const GameEndedInTie = { tag: "GameEndedInTie" };

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant("Waiting", AlgebraicType.createProductType([])),
      new SumTypeVariant("Reset", AlgebraicType.createProductType([])),
      new SumTypeVariant("GameStarted", AlgebraicType.createProductType([])),
      new SumTypeVariant("SpaceScored", AlgebraicType.createProductType([])),
      new SumTypeVariant("TimeScored", AlgebraicType.createProductType([])),
      new SumTypeVariant("GameEndedInSpaceWin", AlgebraicType.createProductType([])),
      new SumTypeVariant("GameEndedInTimeWin", AlgebraicType.createProductType([])),
      new SumTypeVariant("GameEndedInTie", AlgebraicType.createProductType([])),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: GameState): void {
      GameState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): GameState {
      return GameState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

// The tagged union or sum type for the algebraic type `GameState`.
export type GameState = GameState.Waiting | GameState.Reset | GameState.GameStarted | GameState.SpaceScored | GameState.TimeScored | GameState.GameEndedInSpaceWin | GameState.GameEndedInTimeWin | GameState.GameEndedInTie;

export default GameState;

