// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Clock
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "remaning")]
        public float Remaning;

        public Clock(
            byte Id,
            float Remaning
        )
        {
            this.Id = Id;
            this.Remaning = Remaning;
        }

        public Clock()
        {
        }
    }
}
