// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public enum EntityState
    {
        Spawning,
        ReadyToMove,
        Moving,
        ReadyToThrow,
        Throwing,
        Hit,
        LostGame,
        WonGame,
        Standby,
        Despawning,
    }
}
