// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Identifiable
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "kind")]
        public EntityKind Kind;
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;

        public Identifiable(
            string Name,
            EntityKind Kind,
            SpacetimeDB.Identity Identity
        )
        {
            this.Name = Name;
            this.Kind = Kind;
            this.Identity = Identity;
        }

        public Identifiable()
        {
            this.Name = "";
        }
    }
}
