// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Message
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "text")]
        public string Text;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;

        public Message(
            string Name,
            string Text,
            SpacetimeDB.Timestamp Timestamp
        )
        {
            this.Name = Name;
            this.Text = Text;
            this.Timestamp = Timestamp;
        }

        public Message()
        {
            this.Name = "";
            this.Text = "";
        }
    }
}
