// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Movable
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "kind")]
        public EntityKind Kind;
        [DataMember(Name = "state")]
        public EntityState State;
        [DataMember(Name = "position")]
        public Vector3D Position;
        [DataMember(Name = "velocity")]
        public Vector3D Velocity;

        public Movable(
            string Name,
            EntityKind Kind,
            EntityState State,
            Vector3D Position,
            Vector3D Velocity
        )
        {
            this.Name = Name;
            this.Kind = Kind;
            this.State = State;
            this.Position = Position;
            this.Velocity = Velocity;
        }

        public Movable()
        {
            this.Name = "";
            this.Position = new();
            this.Velocity = new();
        }
    }
}
