// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Pingable
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "timestamp")]
        public long Timestamp;

        public Pingable(
            string Name,
            long Timestamp
        )
        {
            this.Name = Name;
            this.Timestamp = Timestamp;
        }

        public Pingable()
        {
            this.Name = "";
        }
    }
}
