// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Routable
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "counter")]
        public byte Counter;
        [DataMember(Name = "destination")]
        public Vector3D Destination;
        [DataMember(Name = "action")]
        public RouteAction Action;

        public Routable(
            string Name,
            byte Counter,
            Vector3D Destination,
            RouteAction Action
        )
        {
            this.Name = Name;
            this.Counter = Counter;
            this.Destination = Destination;
            this.Action = Action;
        }

        public Routable()
        {
            this.Name = "";
            this.Destination = new();
        }
    }
}
