// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearIdentityArgs {
    pub name: String,
}

impl From<ClearIdentityArgs> for super::Reducer {
    fn from(args: ClearIdentityArgs) -> Self {
        Self::ClearIdentity { name: args.name }
    }
}

impl __sdk::InModule for ClearIdentityArgs {
    type Module = super::RemoteModule;
}

pub struct ClearIdentityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_identity {
    /// Request that the remote module invoke the reducer `clear_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_clear_identity`] callbacks.
    fn clear_identity(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_identity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClearIdentityCallbackId`] can be passed to [`Self::remove_on_clear_identity`]
    /// to cancel the callback.
    fn on_clear_identity(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> ClearIdentityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_clear_identity`],
    /// causing it not to run in the future.
    fn remove_on_clear_identity(&self, callback: ClearIdentityCallbackId);
}

impl clear_identity for super::RemoteReducers {
    fn clear_identity(&self, name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("clear_identity", ClearIdentityArgs { name })
    }
    fn on_clear_identity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> ClearIdentityCallbackId {
        ClearIdentityCallbackId(self.imp.on_reducer(
            "clear_identity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClearIdentity { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_clear_identity(&self, callback: ClearIdentityCallbackId) {
        self.imp.remove_on_reducer("clear_identity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `clear_identity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_clear_identity {
    /// Set the call-reducer flags for the reducer `clear_identity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn clear_identity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_clear_identity for super::SetReducerFlags {
    fn clear_identity(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("clear_identity", flags);
    }
}
