// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearAllIdentitiesArgs {}

impl From<ClearAllIdentitiesArgs> for super::Reducer {
    fn from(args: ClearAllIdentitiesArgs) -> Self {
        Self::ClearAllIdentities
    }
}

impl __sdk::InModule for ClearAllIdentitiesArgs {
    type Module = super::RemoteModule;
}

pub struct ClearAllIdentitiesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_all_identities`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_all_identities {
    /// Request that the remote module invoke the reducer `clear_all_identities` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_clear_all_identities`] callbacks.
    fn clear_all_identities(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_all_identities`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClearAllIdentitiesCallbackId`] can be passed to [`Self::remove_on_clear_all_identities`]
    /// to cancel the callback.
    fn on_clear_all_identities(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearAllIdentitiesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_clear_all_identities`],
    /// causing it not to run in the future.
    fn remove_on_clear_all_identities(&self, callback: ClearAllIdentitiesCallbackId);
}

impl clear_all_identities for super::RemoteReducers {
    fn clear_all_identities(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("clear_all_identities", ClearAllIdentitiesArgs {})
    }
    fn on_clear_all_identities(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearAllIdentitiesCallbackId {
        ClearAllIdentitiesCallbackId(self.imp.on_reducer(
            "clear_all_identities",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClearAllIdentities {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_clear_all_identities(&self, callback: ClearAllIdentitiesCallbackId) {
        self.imp
            .remove_on_reducer("clear_all_identities", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `clear_all_identities`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_clear_all_identities {
    /// Set the call-reducer flags for the reducer `clear_all_identities` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn clear_all_identities(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_clear_all_identities for super::SetReducerFlags {
    fn clear_all_identities(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("clear_all_identities", flags);
    }
}
