// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::clock_type::Clock;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `clocks`.
///
/// Obtain a handle from the [`ClocksTableAccess::clocks`] method on [`super::RemoteTables`],
/// like `ctx.db.clocks()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.clocks().on_insert(...)`.
pub struct ClocksTableHandle<'ctx> {
    imp: __sdk::TableHandle<Clock>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `clocks`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ClocksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ClocksTableHandle`], which mediates access to the table `clocks`.
    fn clocks(&self) -> ClocksTableHandle<'_>;
}

impl ClocksTableAccess for super::RemoteTables {
    fn clocks(&self) -> ClocksTableHandle<'_> {
        ClocksTableHandle {
            imp: self.imp.get_table::<Clock>("clocks"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ClocksInsertCallbackId(__sdk::CallbackId);
pub struct ClocksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ClocksTableHandle<'ctx> {
    type Row = Clock;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Clock> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ClocksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClocksInsertCallbackId {
        ClocksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ClocksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ClocksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ClocksDeleteCallbackId {
        ClocksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ClocksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Clock>("clocks");
    _table.add_unique_constraint::<u8>("id", |row| &row.id);
}
pub struct ClocksUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ClocksTableHandle<'ctx> {
    type UpdateCallbackId = ClocksUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ClocksUpdateCallbackId {
        ClocksUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ClocksUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Clock>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Clock>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `clocks`,
/// which allows point queries on the field of the same name
/// via the [`ClocksIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.clocks().id().find(...)`.
pub struct ClocksIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Clock, u8>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ClocksTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `clocks`.
    pub fn id(&self) -> ClocksIdUnique<'ctx> {
        ClocksIdUnique {
            imp: self.imp.get_unique_constraint::<u8>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ClocksIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u8) -> Option<Clock> {
        self.imp.find(col_val)
    }
}
