// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::game_state_type::GameState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Game {
    pub id: u8,
    pub name: String,
    pub space_score: i32,
    pub time_score: i32,
    pub remaining: i8,
    pub state: GameState,
    pub mvp: String,
}

impl __sdk::InModule for Game {
    type Module = super::RemoteModule;
}
