// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_kind_type::EntityKind;
use super::identifiable_type::Identifiable;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `identifiables`.
///
/// Obtain a handle from the [`IdentifiablesTableAccess::identifiables`] method on [`super::RemoteTables`],
/// like `ctx.db.identifiables()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.identifiables().on_insert(...)`.
pub struct IdentifiablesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Identifiable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `identifiables`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IdentifiablesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IdentifiablesTableHandle`], which mediates access to the table `identifiables`.
    fn identifiables(&self) -> IdentifiablesTableHandle<'_>;
}

impl IdentifiablesTableAccess for super::RemoteTables {
    fn identifiables(&self) -> IdentifiablesTableHandle<'_> {
        IdentifiablesTableHandle {
            imp: self.imp.get_table::<Identifiable>("identifiables"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IdentifiablesInsertCallbackId(__sdk::CallbackId);
pub struct IdentifiablesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IdentifiablesTableHandle<'ctx> {
    type Row = Identifiable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Identifiable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IdentifiablesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IdentifiablesInsertCallbackId {
        IdentifiablesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IdentifiablesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IdentifiablesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IdentifiablesDeleteCallbackId {
        IdentifiablesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IdentifiablesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Identifiable>("identifiables");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct IdentifiablesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IdentifiablesTableHandle<'ctx> {
    type UpdateCallbackId = IdentifiablesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IdentifiablesUpdateCallbackId {
        IdentifiablesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IdentifiablesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Identifiable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Identifiable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `name` unique index on the table `identifiables`,
/// which allows point queries on the field of the same name
/// via the [`IdentifiablesNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.identifiables().name().find(...)`.
pub struct IdentifiablesNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Identifiable, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IdentifiablesTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `identifiables`.
    pub fn name(&self) -> IdentifiablesNameUnique<'ctx> {
        IdentifiablesNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IdentifiablesNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Identifiable> {
        self.imp.find(col_val)
    }
}
