// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImpulseArgs {
    pub name: String,
    pub x: f32,
    pub y: f32,
}

impl From<ImpulseArgs> for super::Reducer {
    fn from(args: ImpulseArgs) -> Self {
        Self::Impulse {
            name: args.name,
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for ImpulseArgs {
    type Module = super::RemoteModule;
}

pub struct ImpulseCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `impulse`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait impulse {
    /// Request that the remote module invoke the reducer `impulse` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_impulse`] callbacks.
    fn impulse(&self, name: String, x: f32, y: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `impulse`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImpulseCallbackId`] can be passed to [`Self::remove_on_impulse`]
    /// to cancel the callback.
    fn on_impulse(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &f32, &f32) + Send + 'static,
    ) -> ImpulseCallbackId;
    /// Cancel a callback previously registered by [`Self::on_impulse`],
    /// causing it not to run in the future.
    fn remove_on_impulse(&self, callback: ImpulseCallbackId);
}

impl impulse for super::RemoteReducers {
    fn impulse(&self, name: String, x: f32, y: f32) -> __sdk::Result<()> {
        self.imp.call_reducer("impulse", ImpulseArgs { name, x, y })
    }
    fn on_impulse(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &f32, &f32) + Send + 'static,
    ) -> ImpulseCallbackId {
        ImpulseCallbackId(self.imp.on_reducer(
            "impulse",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Impulse { name, x, y },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name, x, y)
            }),
        ))
    }
    fn remove_on_impulse(&self, callback: ImpulseCallbackId) {
        self.imp.remove_on_reducer("impulse", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `impulse`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_impulse {
    /// Set the call-reducer flags for the reducer `impulse` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn impulse(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_impulse for super::SetReducerFlags {
    fn impulse(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("impulse", flags);
    }
}
