// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct JoinArgs {
    pub name: String,
}

impl From<JoinArgs> for super::Reducer {
    fn from(args: JoinArgs) -> Self {
        Self::Join { name: args.name }
    }
}

impl __sdk::InModule for JoinArgs {
    type Module = super::RemoteModule;
}

pub struct JoinCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `join`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait join {
    /// Request that the remote module invoke the reducer `join` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_join`] callbacks.
    fn join(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `join`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`JoinCallbackId`] can be passed to [`Self::remove_on_join`]
    /// to cancel the callback.
    fn on_join(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> JoinCallbackId;
    /// Cancel a callback previously registered by [`Self::on_join`],
    /// causing it not to run in the future.
    fn remove_on_join(&self, callback: JoinCallbackId);
}

impl join for super::RemoteReducers {
    fn join(&self, name: String) -> __sdk::Result<()> {
        self.imp.call_reducer("join", JoinArgs { name })
    }
    fn on_join(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> JoinCallbackId {
        JoinCallbackId(self.imp.on_reducer(
            "join",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Join { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_join(&self, callback: JoinCallbackId) {
        self.imp.remove_on_reducer("join", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `join`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_join {
    /// Set the call-reducer flags for the reducer `join` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn join(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_join for super::SetReducerFlags {
    fn join(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("join", flags);
    }
}
