// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::entity_kind_type::EntityKind;
use super::entity_state_type::EntityState;
use super::vector_3_d_type::Vector3D;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Movable {
    pub name: String,
    pub kind: EntityKind,
    pub state: EntityState,
    pub position: Vector3D,
    pub velocity: Vector3D,
}

impl __sdk::InModule for Movable {
    type Module = super::RemoteModule;
}
