// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::entity_kind_type::EntityKind;
use super::entity_state_type::EntityState;
use super::movable_type::Movable;
use super::vector_3_d_type::Vector3D;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `movables`.
///
/// Obtain a handle from the [`MovablesTableAccess::movables`] method on [`super::RemoteTables`],
/// like `ctx.db.movables()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movables().on_insert(...)`.
pub struct MovablesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Movable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `movables`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MovablesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MovablesTableHandle`], which mediates access to the table `movables`.
    fn movables(&self) -> MovablesTableHandle<'_>;
}

impl MovablesTableAccess for super::RemoteTables {
    fn movables(&self) -> MovablesTableHandle<'_> {
        MovablesTableHandle {
            imp: self.imp.get_table::<Movable>("movables"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MovablesInsertCallbackId(__sdk::CallbackId);
pub struct MovablesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MovablesTableHandle<'ctx> {
    type Row = Movable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Movable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MovablesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovablesInsertCallbackId {
        MovablesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MovablesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MovablesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MovablesDeleteCallbackId {
        MovablesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MovablesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Movable>("movables");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct MovablesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MovablesTableHandle<'ctx> {
    type UpdateCallbackId = MovablesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MovablesUpdateCallbackId {
        MovablesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MovablesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Movable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Movable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `name` unique index on the table `movables`,
/// which allows point queries on the field of the same name
/// via the [`MovablesNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.movables().name().find(...)`.
pub struct MovablesNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Movable, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MovablesTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `movables`.
    pub fn name(&self) -> MovablesNameUnique<'ctx> {
        MovablesNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MovablesNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Movable> {
        self.imp.find(col_val)
    }
}
