// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PingArgs {
    pub timestamp: i64,
}

impl From<PingArgs> for super::Reducer {
    fn from(args: PingArgs) -> Self {
        Self::Ping {
            timestamp: args.timestamp,
        }
    }
}

impl __sdk::InModule for PingArgs {
    type Module = super::RemoteModule;
}

pub struct PingCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ping`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ping {
    /// Request that the remote module invoke the reducer `ping` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_ping`] callbacks.
    fn ping(&self, timestamp: i64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `ping`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PingCallbackId`] can be passed to [`Self::remove_on_ping`]
    /// to cancel the callback.
    fn on_ping(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i64) + Send + 'static,
    ) -> PingCallbackId;
    /// Cancel a callback previously registered by [`Self::on_ping`],
    /// causing it not to run in the future.
    fn remove_on_ping(&self, callback: PingCallbackId);
}

impl ping for super::RemoteReducers {
    fn ping(&self, timestamp: i64) -> __sdk::Result<()> {
        self.imp.call_reducer("ping", PingArgs { timestamp })
    }
    fn on_ping(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i64) + Send + 'static,
    ) -> PingCallbackId {
        PingCallbackId(self.imp.on_reducer(
            "ping",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Ping { timestamp },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timestamp)
            }),
        ))
    }
    fn remove_on_ping(&self, callback: PingCallbackId) {
        self.imp.remove_on_reducer("ping", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `ping`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_ping {
    /// Set the call-reducer flags for the reducer `ping` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn ping(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_ping for super::SetReducerFlags {
    fn ping(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("ping", flags);
    }
}
