// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::pingable_type::Pingable;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `pingables`.
///
/// Obtain a handle from the [`PingablesTableAccess::pingables`] method on [`super::RemoteTables`],
/// like `ctx.db.pingables()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pingables().on_insert(...)`.
pub struct PingablesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Pingable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `pingables`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PingablesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PingablesTableHandle`], which mediates access to the table `pingables`.
    fn pingables(&self) -> PingablesTableHandle<'_>;
}

impl PingablesTableAccess for super::RemoteTables {
    fn pingables(&self) -> PingablesTableHandle<'_> {
        PingablesTableHandle {
            imp: self.imp.get_table::<Pingable>("pingables"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PingablesInsertCallbackId(__sdk::CallbackId);
pub struct PingablesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PingablesTableHandle<'ctx> {
    type Row = Pingable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Pingable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PingablesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PingablesInsertCallbackId {
        PingablesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PingablesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PingablesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PingablesDeleteCallbackId {
        PingablesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PingablesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Pingable>("pingables");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct PingablesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PingablesTableHandle<'ctx> {
    type UpdateCallbackId = PingablesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PingablesUpdateCallbackId {
        PingablesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PingablesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Pingable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Pingable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `name` unique index on the table `pingables`,
/// which allows point queries on the field of the same name
/// via the [`PingablesNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.pingables().name().find(...)`.
pub struct PingablesNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Pingable, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PingablesTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `pingables`.
    pub fn name(&self) -> PingablesNameUnique<'ctx> {
        PingablesNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PingablesNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Pingable> {
        self.imp.find(col_val)
    }
}
