// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveAllBallsArgs {}

impl From<RemoveAllBallsArgs> for super::Reducer {
    fn from(args: RemoveAllBallsArgs) -> Self {
        Self::RemoveAllBalls
    }
}

impl __sdk::InModule for RemoveAllBallsArgs {
    type Module = super::RemoteModule;
}

pub struct RemoveAllBallsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_all_balls`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_all_balls {
    /// Request that the remote module invoke the reducer `remove_all_balls` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_remove_all_balls`] callbacks.
    fn remove_all_balls(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_all_balls`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RemoveAllBallsCallbackId`] can be passed to [`Self::remove_on_remove_all_balls`]
    /// to cancel the callback.
    fn on_remove_all_balls(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> RemoveAllBallsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_remove_all_balls`],
    /// causing it not to run in the future.
    fn remove_on_remove_all_balls(&self, callback: RemoveAllBallsCallbackId);
}

impl remove_all_balls for super::RemoteReducers {
    fn remove_all_balls(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("remove_all_balls", RemoveAllBallsArgs {})
    }
    fn on_remove_all_balls(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> RemoveAllBallsCallbackId {
        RemoveAllBallsCallbackId(self.imp.on_reducer(
            "remove_all_balls",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RemoveAllBalls {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_remove_all_balls(&self, callback: RemoveAllBallsCallbackId) {
        self.imp.remove_on_reducer("remove_all_balls", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `remove_all_balls`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_remove_all_balls {
    /// Set the call-reducer flags for the reducer `remove_all_balls` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn remove_all_balls(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_remove_all_balls for super::SetReducerFlags {
    fn remove_all_balls(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("remove_all_balls", flags);
    }
}
