// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::route_action_type::RouteAction;
use super::vector_3_d_type::Vector3D;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Routable {
    pub name: String,
    pub counter: u8,
    pub destination: Vector3D,
    pub action: RouteAction,
}

impl __sdk::InModule for Routable {
    type Module = super::RemoteModule;
}
