// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::routable_type::Routable;
use super::route_action_type::RouteAction;
use super::vector_3_d_type::Vector3D;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `routables`.
///
/// Obtain a handle from the [`RoutablesTableAccess::routables`] method on [`super::RemoteTables`],
/// like `ctx.db.routables()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.routables().on_insert(...)`.
pub struct RoutablesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Routable>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `routables`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RoutablesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RoutablesTableHandle`], which mediates access to the table `routables`.
    fn routables(&self) -> RoutablesTableHandle<'_>;
}

impl RoutablesTableAccess for super::RemoteTables {
    fn routables(&self) -> RoutablesTableHandle<'_> {
        RoutablesTableHandle {
            imp: self.imp.get_table::<Routable>("routables"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RoutablesInsertCallbackId(__sdk::CallbackId);
pub struct RoutablesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RoutablesTableHandle<'ctx> {
    type Row = Routable;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Routable> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RoutablesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoutablesInsertCallbackId {
        RoutablesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RoutablesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RoutablesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RoutablesDeleteCallbackId {
        RoutablesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RoutablesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Routable>("routables");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct RoutablesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RoutablesTableHandle<'ctx> {
    type UpdateCallbackId = RoutablesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RoutablesUpdateCallbackId {
        RoutablesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RoutablesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Routable>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Routable>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `name` unique index on the table `routables`,
/// which allows point queries on the field of the same name
/// via the [`RoutablesNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.routables().name().find(...)`.
pub struct RoutablesNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Routable, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RoutablesTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `routables`.
    pub fn name(&self) -> RoutablesNameUnique<'ctx> {
        RoutablesNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RoutablesNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Routable> {
        self.imp.find(col_val)
    }
}
