// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SayArgs {
    pub text: String,
}

impl From<SayArgs> for super::Reducer {
    fn from(args: SayArgs) -> Self {
        Self::Say { text: args.text }
    }
}

impl __sdk::InModule for SayArgs {
    type Module = super::RemoteModule;
}

pub struct SayCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `say`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait say {
    /// Request that the remote module invoke the reducer `say` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_say`] callbacks.
    fn say(&self, text: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `say`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SayCallbackId`] can be passed to [`Self::remove_on_say`]
    /// to cancel the callback.
    fn on_say(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SayCallbackId;
    /// Cancel a callback previously registered by [`Self::on_say`],
    /// causing it not to run in the future.
    fn remove_on_say(&self, callback: SayCallbackId);
}

impl say for super::RemoteReducers {
    fn say(&self, text: String) -> __sdk::Result<()> {
        self.imp.call_reducer("say", SayArgs { text })
    }
    fn on_say(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SayCallbackId {
        SayCallbackId(self.imp.on_reducer(
            "say",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Say { text },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, text)
            }),
        ))
    }
    fn remove_on_say(&self, callback: SayCallbackId) {
        self.imp.remove_on_reducer("say", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `say`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_say {
    /// Set the call-reducer flags for the reducer `say` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn say(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_say for super::SetReducerFlags {
    fn say(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("say", flags);
    }
}
