// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::schedule_type::Schedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `schedules`.
///
/// Obtain a handle from the [`SchedulesTableAccess::schedules`] method on [`super::RemoteTables`],
/// like `ctx.db.schedules()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.schedules().on_insert(...)`.
pub struct SchedulesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Schedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `schedules`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SchedulesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SchedulesTableHandle`], which mediates access to the table `schedules`.
    fn schedules(&self) -> SchedulesTableHandle<'_>;
}

impl SchedulesTableAccess for super::RemoteTables {
    fn schedules(&self) -> SchedulesTableHandle<'_> {
        SchedulesTableHandle {
            imp: self.imp.get_table::<Schedule>("schedules"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SchedulesInsertCallbackId(__sdk::CallbackId);
pub struct SchedulesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SchedulesTableHandle<'ctx> {
    type Row = Schedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Schedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SchedulesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchedulesInsertCallbackId {
        SchedulesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SchedulesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SchedulesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SchedulesDeleteCallbackId {
        SchedulesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SchedulesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Schedule>("schedules");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SchedulesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SchedulesTableHandle<'ctx> {
    type UpdateCallbackId = SchedulesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SchedulesUpdateCallbackId {
        SchedulesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SchedulesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Schedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Schedule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `schedules`,
/// which allows point queries on the field of the same name
/// via the [`SchedulesScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.schedules().scheduled_id().find(...)`.
pub struct SchedulesScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Schedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SchedulesTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `schedules`.
    pub fn scheduled_id(&self) -> SchedulesScheduledIdUnique<'ctx> {
        SchedulesScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SchedulesScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Schedule> {
        self.imp.find(col_val)
    }
}
