// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetGameAutoStartArgs {
    pub enable: bool,
}

impl From<SetGameAutoStartArgs> for super::Reducer {
    fn from(args: SetGameAutoStartArgs) -> Self {
        Self::SetGameAutoStart {
            enable: args.enable,
        }
    }
}

impl __sdk::InModule for SetGameAutoStartArgs {
    type Module = super::RemoteModule;
}

pub struct SetGameAutoStartCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_game_auto_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_game_auto_start {
    /// Request that the remote module invoke the reducer `set_game_auto_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_game_auto_start`] callbacks.
    fn set_game_auto_start(&self, enable: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_game_auto_start`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetGameAutoStartCallbackId`] can be passed to [`Self::remove_on_set_game_auto_start`]
    /// to cancel the callback.
    fn on_set_game_auto_start(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetGameAutoStartCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_game_auto_start`],
    /// causing it not to run in the future.
    fn remove_on_set_game_auto_start(&self, callback: SetGameAutoStartCallbackId);
}

impl set_game_auto_start for super::RemoteReducers {
    fn set_game_auto_start(&self, enable: bool) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_game_auto_start", SetGameAutoStartArgs { enable })
    }
    fn on_set_game_auto_start(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool) + Send + 'static,
    ) -> SetGameAutoStartCallbackId {
        SetGameAutoStartCallbackId(self.imp.on_reducer(
            "set_game_auto_start",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetGameAutoStart { enable },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, enable)
            }),
        ))
    }
    fn remove_on_set_game_auto_start(&self, callback: SetGameAutoStartCallbackId) {
        self.imp
            .remove_on_reducer("set_game_auto_start", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_game_auto_start`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_game_auto_start {
    /// Set the call-reducer flags for the reducer `set_game_auto_start` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_game_auto_start(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_game_auto_start for super::SetReducerFlags {
    fn set_game_auto_start(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("set_game_auto_start", flags);
    }
}
