// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnSpaceBallsArgs {
    pub count: u8,
}

impl From<SpawnSpaceBallsArgs> for super::Reducer {
    fn from(args: SpawnSpaceBallsArgs) -> Self {
        Self::SpawnSpaceBalls { count: args.count }
    }
}

impl __sdk::InModule for SpawnSpaceBallsArgs {
    type Module = super::RemoteModule;
}

pub struct SpawnSpaceBallsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_space_balls`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_space_balls {
    /// Request that the remote module invoke the reducer `spawn_space_balls` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_spawn_space_balls`] callbacks.
    fn spawn_space_balls(&self, count: u8) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `spawn_space_balls`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SpawnSpaceBallsCallbackId`] can be passed to [`Self::remove_on_spawn_space_balls`]
    /// to cancel the callback.
    fn on_spawn_space_balls(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> SpawnSpaceBallsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_spawn_space_balls`],
    /// causing it not to run in the future.
    fn remove_on_spawn_space_balls(&self, callback: SpawnSpaceBallsCallbackId);
}

impl spawn_space_balls for super::RemoteReducers {
    fn spawn_space_balls(&self, count: u8) -> __sdk::Result<()> {
        self.imp
            .call_reducer("spawn_space_balls", SpawnSpaceBallsArgs { count })
    }
    fn on_spawn_space_balls(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u8) + Send + 'static,
    ) -> SpawnSpaceBallsCallbackId {
        SpawnSpaceBallsCallbackId(self.imp.on_reducer(
            "spawn_space_balls",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SpawnSpaceBalls { count },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, count)
            }),
        ))
    }
    fn remove_on_spawn_space_balls(&self, callback: SpawnSpaceBallsCallbackId) {
        self.imp.remove_on_reducer("spawn_space_balls", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `spawn_space_balls`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_spawn_space_balls {
    /// Set the call-reducer flags for the reducer `spawn_space_balls` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn spawn_space_balls(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_spawn_space_balls for super::SetReducerFlags {
    fn spawn_space_balls(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("spawn_space_balls", flags);
    }
}
