// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stat_type::Stat;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `stats`.
///
/// Obtain a handle from the [`StatsTableAccess::stats`] method on [`super::RemoteTables`],
/// like `ctx.db.stats()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stats().on_insert(...)`.
pub struct StatsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Stat>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `stats`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StatsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StatsTableHandle`], which mediates access to the table `stats`.
    fn stats(&self) -> StatsTableHandle<'_>;
}

impl StatsTableAccess for super::RemoteTables {
    fn stats(&self) -> StatsTableHandle<'_> {
        StatsTableHandle {
            imp: self.imp.get_table::<Stat>("stats"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StatsInsertCallbackId(__sdk::CallbackId);
pub struct StatsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StatsTableHandle<'ctx> {
    type Row = Stat;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Stat> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StatsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsInsertCallbackId {
        StatsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StatsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StatsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StatsDeleteCallbackId {
        StatsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StatsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Stat>("stats");
    _table.add_unique_constraint::<String>("name", |row| &row.name);
}
pub struct StatsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StatsTableHandle<'ctx> {
    type UpdateCallbackId = StatsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StatsUpdateCallbackId {
        StatsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StatsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Stat>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Stat>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `name` unique index on the table `stats`,
/// which allows point queries on the field of the same name
/// via the [`StatsNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.stats().name().find(...)`.
pub struct StatsNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Stat, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StatsTableHandle<'ctx> {
    /// Get a handle on the `name` unique index on the table `stats`.
    pub fn name(&self) -> StatsNameUnique<'ctx> {
        StatsNameUnique {
            imp: self.imp.get_unique_constraint::<String>("name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StatsNameUnique<'ctx> {
    /// Find the subscribed row whose `name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Stat> {
        self.imp.find(col_val)
    }
}
