// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ThrowToArgs {
    pub x: f32,
    pub y: f32,
}

impl From<ThrowToArgs> for super::Reducer {
    fn from(args: ThrowToArgs) -> Self {
        Self::ThrowTo {
            x: args.x,
            y: args.y,
        }
    }
}

impl __sdk::InModule for ThrowToArgs {
    type Module = super::RemoteModule;
}

pub struct ThrowToCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `throw_to`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait throw_to {
    /// Request that the remote module invoke the reducer `throw_to` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_throw_to`] callbacks.
    fn throw_to(&self, x: f32, y: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `throw_to`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ThrowToCallbackId`] can be passed to [`Self::remove_on_throw_to`]
    /// to cancel the callback.
    fn on_throw_to(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowToCallbackId;
    /// Cancel a callback previously registered by [`Self::on_throw_to`],
    /// causing it not to run in the future.
    fn remove_on_throw_to(&self, callback: ThrowToCallbackId);
}

impl throw_to for super::RemoteReducers {
    fn throw_to(&self, x: f32, y: f32) -> __sdk::Result<()> {
        self.imp.call_reducer("throw_to", ThrowToArgs { x, y })
    }
    fn on_throw_to(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &f32, &f32) + Send + 'static,
    ) -> ThrowToCallbackId {
        ThrowToCallbackId(self.imp.on_reducer(
            "throw_to",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ThrowTo { x, y },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, x, y)
            }),
        ))
    }
    fn remove_on_throw_to(&self, callback: ThrowToCallbackId) {
        self.imp.remove_on_reducer("throw_to", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `throw_to`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_throw_to {
    /// Set the call-reducer flags for the reducer `throw_to` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn throw_to(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_throw_to for super::SetReducerFlags {
    fn throw_to(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("throw_to", flags);
    }
}
