// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class GamesHandle : RemoteTableHandle<EventContext, Game>
        {
            protected override string RemoteTableName => "games";

            public sealed class IdUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(Game row) => row.Id;

                public IdUniqueIndex(GamesHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal GamesHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(Game row) => row.Id;

        }

        public readonly GamesHandle Games;
    }
}
