// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class IdentifiablesHandle : RemoteTableHandle<EventContext, Identifiable>
        {
            protected override string RemoteTableName => "identifiables";

            public sealed class IdentityIndex : BTreeIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(Identifiable row) => row.Identity;

                public IdentityIndex(IdentifiablesHandle table) : base(table) { }
            }

            public readonly IdentityIndex Identity;

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Identifiable row) => row.Name;

                public NameUniqueIndex(IdentifiablesHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal IdentifiablesHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
                Name = new(this);
            }

            protected override object GetPrimaryKey(Identifiable row) => row.Name;
        }

        public readonly IdentifiablesHandle Identifiables;
    }
}
