// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MessagesHandle : RemoteTableHandle<EventContext, Message>
        {
            protected override string RemoteTableName => "messages";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Message row) => row.Name;

                public NameUniqueIndex(MessagesHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal MessagesHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(Message row) => row.Name;
        }

        public readonly MessagesHandle Messages;
    }
}
