// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MovablesHandle : RemoteTableHandle<EventContext, Movable>
        {
            protected override string RemoteTableName => "movables";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Movable row) => row.Name;

                public NameUniqueIndex(MovablesHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal MovablesHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(Movable row) => row.Name;
        }

        public readonly MovablesHandle Movables;
    }
}
