// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PingablesHandle : RemoteTableHandle<EventContext, Pingable>
        {
            protected override string RemoteTableName => "pingables";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Pingable row) => row.Name;

                public NameUniqueIndex(PingablesHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal PingablesHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(Pingable row) => row.Name;
        }

        public readonly PingablesHandle Pingables;
    }
}
