// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class RoutablesHandle : RemoteTableHandle<EventContext, Routable>
        {
            protected override string RemoteTableName => "routables";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Routable row) => row.Name;

                public NameUniqueIndex(RoutablesHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal RoutablesHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(Routable row) => row.Name;
        }

        public readonly RoutablesHandle Routables;
    }
}
