// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StatsHandle : RemoteTableHandle<EventContext, Stat>
        {
            protected override string RemoteTableName => "stats";

            public sealed class NameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(Stat row) => row.Name;

                public NameUniqueIndex(StatsHandle table) : base(table) { }
            }

            public readonly NameUniqueIndex Name;

            internal StatsHandle(DbConnection conn) : base(conn)
            {
                Name = new(this);
            }

            protected override object GetPrimaryKey(Stat row) => row.Name;
        }

        public readonly StatsHandle Stats;
    }
}
