// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearIdentityHandler(ReducerEventContext ctx, string name);
        public event ClearIdentityHandler? OnClearIdentity;

        public void ClearIdentity(string name)
        {
            conn.InternalCallReducer(new Reducer.ClearIdentity(name), this.SetCallReducerFlags.ClearIdentityFlags);
        }

        public bool InvokeClearIdentity(ReducerEventContext ctx, Reducer.ClearIdentity args)
        {
            if (OnClearIdentity == null) return false;
            OnClearIdentity(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearIdentity : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public ClearIdentity(string Name)
            {
                this.Name = Name;
            }

            public ClearIdentity()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "clear_identity";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearIdentityFlags;
        public void ClearIdentity(CallReducerFlags flags) => ClearIdentityFlags = flags;
    }
}
