// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClearAllIdentitiesHandler(ReducerEventContext ctx);
        public event ClearAllIdentitiesHandler? OnClearAllIdentities;

        public void ClearAllIdentities()
        {
            conn.InternalCallReducer(new Reducer.ClearAllIdentities(), this.SetCallReducerFlags.ClearAllIdentitiesFlags);
        }

        public bool InvokeClearAllIdentities(ReducerEventContext ctx, Reducer.ClearAllIdentities args)
        {
            if (OnClearAllIdentities == null) return false;
            OnClearAllIdentities(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClearAllIdentities : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "clear_all_identities";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClearAllIdentitiesFlags;
        public void ClearAllIdentities(CallReducerFlags flags) => ClearAllIdentitiesFlags = flags;
    }
}
