// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImpulseHandler(ReducerEventContext ctx, string name, float x, float y);
        public event ImpulseHandler? OnImpulse;

        public void Impulse(string name, float x, float y)
        {
            conn.InternalCallReducer(new Reducer.Impulse(name, x, y), this.SetCallReducerFlags.ImpulseFlags);
        }

        public bool InvokeImpulse(ReducerEventContext ctx, Reducer.Impulse args)
        {
            if (OnImpulse == null) return false;
            OnImpulse(
                ctx,
                args.Name,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Impulse : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;

            public Impulse(
                string Name,
                float X,
                float Y
            )
            {
                this.Name = Name;
                this.X = X;
                this.Y = Y;
            }

            public Impulse()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "impulse";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImpulseFlags;
        public void Impulse(CallReducerFlags flags) => ImpulseFlags = flags;
    }
}
