// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImpulseAllBallsHandler(ReducerEventContext ctx);
        public event ImpulseAllBallsHandler? OnImpulseAllBalls;

        public void ImpulseAllBalls()
        {
            conn.InternalCallReducer(new Reducer.ImpulseAllBalls(), this.SetCallReducerFlags.ImpulseAllBallsFlags);
        }

        public bool InvokeImpulseAllBalls(ReducerEventContext ctx, Reducer.ImpulseAllBalls args)
        {
            if (OnImpulseAllBalls == null) return false;
            OnImpulseAllBalls(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImpulseAllBalls : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "impulse_all_balls";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImpulseAllBallsFlags;
        public void ImpulseAllBalls(CallReducerFlags flags) => ImpulseAllBallsFlags = flags;
    }
}
