// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void JoinHandler(ReducerEventContext ctx, string name);
        public event JoinHandler? OnJoin;

        public void Join(string name)
        {
            conn.InternalCallReducer(new Reducer.Join(name), this.SetCallReducerFlags.JoinFlags);
        }

        public bool InvokeJoin(ReducerEventContext ctx, Reducer.Join args)
        {
            if (OnJoin == null) return false;
            OnJoin(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Join : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public Join(string Name)
            {
                this.Name = Name;
            }

            public Join()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "join";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags JoinFlags;
        public void Join(CallReducerFlags flags) => JoinFlags = flags;
    }
}
