// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void KickHandler(ReducerEventContext ctx, string name);
        public event KickHandler? OnKick;

        public void Kick(string name)
        {
            conn.InternalCallReducer(new Reducer.Kick(name), this.SetCallReducerFlags.KickFlags);
        }

        public bool InvokeKick(ReducerEventContext ctx, Reducer.Kick args)
        {
            if (OnKick == null) return false;
            OnKick(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Kick : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public Kick(string Name)
            {
                this.Name = Name;
            }

            public Kick()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "kick";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags KickFlags;
        public void Kick(CallReducerFlags flags) => KickFlags = flags;
    }
}
