// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PingHandler(ReducerEventContext ctx, long timestamp);
        public event PingHandler? OnPing;

        public void Ping(long timestamp)
        {
            conn.InternalCallReducer(new Reducer.Ping(timestamp), this.SetCallReducerFlags.PingFlags);
        }

        public bool InvokePing(ReducerEventContext ctx, Reducer.Ping args)
        {
            if (OnPing == null) return false;
            OnPing(
                ctx,
                args.Timestamp
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Ping : Reducer, IReducerArgs
        {
            [DataMember(Name = "timestamp")]
            public long Timestamp;

            public Ping(long Timestamp)
            {
                this.Timestamp = Timestamp;
            }

            public Ping()
            {
            }

            string IReducerArgs.ReducerName => "ping";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PingFlags;
        public void Ping(CallReducerFlags flags) => PingFlags = flags;
    }
}
