// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveAllBallsHandler(ReducerEventContext ctx);
        public event RemoveAllBallsHandler? OnRemoveAllBalls;

        public void RemoveAllBalls()
        {
            conn.InternalCallReducer(new Reducer.RemoveAllBalls(), this.SetCallReducerFlags.RemoveAllBallsFlags);
        }

        public bool InvokeRemoveAllBalls(ReducerEventContext ctx, Reducer.RemoveAllBalls args)
        {
            if (OnRemoveAllBalls == null) return false;
            OnRemoveAllBalls(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveAllBalls : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "remove_all_balls";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemoveAllBallsFlags;
        public void RemoveAllBalls(CallReducerFlags flags) => RemoveAllBallsFlags = flags;
    }
}
