// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SayHandler(ReducerEventContext ctx, string text);
        public event SayHandler? OnSay;

        public void Say(string text)
        {
            conn.InternalCallReducer(new Reducer.Say(text), this.SetCallReducerFlags.SayFlags);
        }

        public bool InvokeSay(ReducerEventContext ctx, Reducer.Say args)
        {
            if (OnSay == null) return false;
            OnSay(
                ctx,
                args.Text
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Say : Reducer, IReducerArgs
        {
            [DataMember(Name = "text")]
            public string Text;

            public Say(string Text)
            {
                this.Text = Text;
            }

            public Say()
            {
                this.Text = "";
            }

            string IReducerArgs.ReducerName => "say";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SayFlags;
        public void Say(CallReducerFlags flags) => SayFlags = flags;
    }
}
