// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetGameAutoStartHandler(ReducerEventContext ctx, bool enable);
        public event SetGameAutoStartHandler? OnSetGameAutoStart;

        public void SetGameAutoStart(bool enable)
        {
            conn.InternalCallReducer(new Reducer.SetGameAutoStart(enable), this.SetCallReducerFlags.SetGameAutoStartFlags);
        }

        public bool InvokeSetGameAutoStart(ReducerEventContext ctx, Reducer.SetGameAutoStart args)
        {
            if (OnSetGameAutoStart == null) return false;
            OnSetGameAutoStart(
                ctx,
                args.Enable
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetGameAutoStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "enable")]
            public bool Enable;

            public SetGameAutoStart(bool Enable)
            {
                this.Enable = Enable;
            }

            public SetGameAutoStart()
            {
            }

            string IReducerArgs.ReducerName => "set_game_auto_start";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetGameAutoStartFlags;
        public void SetGameAutoStart(CallReducerFlags flags) => SetGameAutoStartFlags = flags;
    }
}
