// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnAllBallsHandler(ReducerEventContext ctx, byte count);
        public event SpawnAllBallsHandler? OnSpawnAllBalls;

        public void SpawnAllBalls(byte count)
        {
            conn.InternalCallReducer(new Reducer.SpawnAllBalls(count), this.SetCallReducerFlags.SpawnAllBallsFlags);
        }

        public bool InvokeSpawnAllBalls(ReducerEventContext ctx, Reducer.SpawnAllBalls args)
        {
            if (OnSpawnAllBalls == null) return false;
            OnSpawnAllBalls(
                ctx,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnAllBalls : Reducer, IReducerArgs
        {
            [DataMember(Name = "count")]
            public byte Count;

            public SpawnAllBalls(byte Count)
            {
                this.Count = Count;
            }

            public SpawnAllBalls()
            {
            }

            string IReducerArgs.ReducerName => "spawn_all_balls";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnAllBallsFlags;
        public void SpawnAllBalls(CallReducerFlags flags) => SpawnAllBallsFlags = flags;
    }
}
