// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnTimeBallsHandler(ReducerEventContext ctx, byte count);
        public event SpawnTimeBallsHandler? OnSpawnTimeBalls;

        public void SpawnTimeBalls(byte count)
        {
            conn.InternalCallReducer(new Reducer.SpawnTimeBalls(count), this.SetCallReducerFlags.SpawnTimeBallsFlags);
        }

        public bool InvokeSpawnTimeBalls(ReducerEventContext ctx, Reducer.SpawnTimeBalls args)
        {
            if (OnSpawnTimeBalls == null) return false;
            OnSpawnTimeBalls(
                ctx,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnTimeBalls : Reducer, IReducerArgs
        {
            [DataMember(Name = "count")]
            public byte Count;

            public SpawnTimeBalls(byte Count)
            {
                this.Count = Count;
            }

            public SpawnTimeBalls()
            {
            }

            string IReducerArgs.ReducerName => "spawn_time_balls";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnTimeBallsFlags;
        public void SpawnTimeBalls(CallReducerFlags flags) => SpawnTimeBallsFlags = flags;
    }
}
