// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnSpaceBallsHandler(ReducerEventContext ctx, byte count);
        public event SpawnSpaceBallsHandler? OnSpawnSpaceBalls;

        public void SpawnSpaceBalls(byte count)
        {
            conn.InternalCallReducer(new Reducer.SpawnSpaceBalls(count), this.SetCallReducerFlags.SpawnSpaceBallsFlags);
        }

        public bool InvokeSpawnSpaceBalls(ReducerEventContext ctx, Reducer.SpawnSpaceBalls args)
        {
            if (OnSpawnSpaceBalls == null) return false;
            OnSpawnSpaceBalls(
                ctx,
                args.Count
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnSpaceBalls : Reducer, IReducerArgs
        {
            [DataMember(Name = "count")]
            public byte Count;

            public SpawnSpaceBalls(byte Count)
            {
                this.Count = Count;
            }

            public SpawnSpaceBalls()
            {
            }

            string IReducerArgs.ReducerName => "spawn_space_balls";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnSpaceBallsFlags;
        public void SpawnSpaceBalls(CallReducerFlags flags) => SpawnSpaceBallsFlags = flags;
    }
}
