// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartInfiniteGameHandler(ReducerEventContext ctx);
        public event StartInfiniteGameHandler? OnStartInfiniteGame;

        public void StartInfiniteGame()
        {
            conn.InternalCallReducer(new Reducer.StartInfiniteGame(), this.SetCallReducerFlags.StartInfiniteGameFlags);
        }

        public bool InvokeStartInfiniteGame(ReducerEventContext ctx, Reducer.StartInfiniteGame args)
        {
            if (OnStartInfiniteGame == null) return false;
            OnStartInfiniteGame(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartInfiniteGame : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "start_infinite_game";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartInfiniteGameFlags;
        public void StartInfiniteGame(CallReducerFlags flags) => StartInfiniteGameFlags = flags;
    }
}
