// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartGameHandler(ReducerEventContext ctx, byte duration);
        public event StartGameHandler? OnStartGame;

        public void StartGame(byte duration)
        {
            conn.InternalCallReducer(new Reducer.StartGame(duration), this.SetCallReducerFlags.StartGameFlags);
        }

        public bool InvokeStartGame(ReducerEventContext ctx, Reducer.StartGame args)
        {
            if (OnStartGame == null) return false;
            OnStartGame(
                ctx,
                args.Duration
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartGame : Reducer, IReducerArgs
        {
            [DataMember(Name = "duration")]
            public byte Duration;

            public StartGame(byte Duration)
            {
                this.Duration = Duration;
            }

            public StartGame()
            {
            }

            string IReducerArgs.ReducerName => "start_game";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartGameFlags;
        public void StartGame(CallReducerFlags flags) => StartGameFlags = flags;
    }
}
