// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TestHandler(ReducerEventContext ctx, string name);
        public event TestHandler? OnTest;

        public void Test(string name)
        {
            conn.InternalCallReducer(new Reducer.Test(name), this.SetCallReducerFlags.TestFlags);
        }

        public bool InvokeTest(ReducerEventContext ctx, Reducer.Test args)
        {
            if (OnTest == null) return false;
            OnTest(
                ctx,
                args.Name
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Test : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;

            public Test(string Name)
            {
                this.Name = Name;
            }

            public Test()
            {
                this.Name = "";
            }

            string IReducerArgs.ReducerName => "test";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TestFlags;
        public void Test(CallReducerFlags flags) => TestFlags = flags;
    }
}
