// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ThrowToHandler(ReducerEventContext ctx, float x, float y);
        public event ThrowToHandler? OnThrowTo;

        public void ThrowTo(float x, float y)
        {
            conn.InternalCallReducer(new Reducer.ThrowTo(x, y), this.SetCallReducerFlags.ThrowToFlags);
        }

        public bool InvokeThrowTo(ReducerEventContext ctx, Reducer.ThrowTo args)
        {
            if (OnThrowTo == null) return false;
            OnThrowTo(
                ctx,
                args.X,
                args.Y
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ThrowTo : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public float X;
            [DataMember(Name = "y")]
            public float Y;

            public ThrowTo(
                float X,
                float Y
            )
            {
                this.X = X;
                this.Y = Y;
            }

            public ThrowTo()
            {
            }

            string IReducerArgs.ReducerName => "throw_to";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ThrowToFlags;
        public void ThrowTo(CallReducerFlags flags) => ThrowToFlags = flags;
    }
}
