// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateHandler(ReducerEventContext ctx, Schedule arg);
        public event UpdateHandler? OnUpdate;

        public void Update(Schedule arg)
        {
            conn.InternalCallReducer(new Reducer.Update(arg), this.SetCallReducerFlags.UpdateFlags);
        }

        public bool InvokeUpdate(ReducerEventContext ctx, Reducer.Update args)
        {
            if (OnUpdate == null) return false;
            OnUpdate(
                ctx,
                args.Arg
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Update : Reducer, IReducerArgs
        {
            [DataMember(Name = "_arg")]
            public Schedule Arg;

            public Update(Schedule Arg)
            {
                this.Arg = Arg;
            }

            public Update()
            {
                this.Arg = new();
            }

            string IReducerArgs.ReducerName => "update";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateFlags;
        public void Update(CallReducerFlags flags) => UpdateFlags = flags;
    }
}
